services:
  ipfs:
    image: ipfs/go-ipfs:master-latest
    container_name: ipfs
    ports:
      - 4001:4001
      - 8080:8080
      - 5001:5001
    volumes:
      - /docker/appdata/ipfs/staging:/export
      - /docker/appdata/ipfs/data:/data/ipfs
    restart: unless-stopped
