#!/usr/bin/env sh

if test -n "$BASH_VERSION"; then
    [ -f "../bash/bash_profile" ] && . "../bash/bash_profile"
elif test -n "$ZSH_VERSION"; then
    [ -f "../zsh/zprofile" ] && . "../zsh/zprofile"
fi

# Explicit XDG_DIRS
XDG_DATA_HOME="$HOME/.local/share"
XDG_CONFIG_HOME="$HOME/.config"
XDG_STATE_HOME="$HOME/.local/state"
XDG_DATA_DIRS="/usr/local/share/:/usr/share/"
XDG_CONFIG_DIRS="/etc/xdg"
XDG_CACHE_HOME="$HOME/.cache"
#XDG_RUNTIME_DIR is set by pam

export XDG_DATA_HOME
export XDG_CONFIG_HOME
export XDG_STATE_HOME
export XDG_DATA_DIRS
export XDG_CONFIG_DIRS
export XDG_CACHE_HOME

# Make XMonad XDG compliant
XMONAD_CONFIG_DIR="$XDG_CONFIG_HOME/xmonad"
XMONAD_DATA_DIR="$XDG_DATA_HOME/xmonad"
XMONAD_CACHE_DIR="$XDG_CACHE_HOME/xmonad"

export XMONAD_CONFIG_DIR
export XMONAD_DATA_DIR
export XMONAD_CACHE_DIR

export PATH="${PATH}:$HOME/.local/bin/:$HOME/.config/emacs/bin/:$HOME/.local/.stack/"
