#!/bin/bash

# Use neovim when possible
command -v nvim >/dev/null && alias vim="nvim" vimdiff="nvim -d"

# Stop making me type sudo >:|
for x in docker timeshift mount umount sv pacman updatedb poweroff shutdown reboot ; do
        alias $x="sudo $x"
done

# Adds verbosity and shorten common commands
alias \
    bup="sudo timeshift --create" \
    res="sudo timeshift --restore" \
    upg="paru -Syu --noconfirm && doom -y upgrade && doom doctor" \
    clr="clear" \
    bat="cat /sys/class/power_supply/BAT?/capacity" \
    cp="cp -iv" \
    mv="mv -iv" \
    rm="rm -v" \
    mkd="mkdir -pv" \
    rmd="rmdir -pv" \
    doomsync="$HOME/.emacs.d/bin/doom sync" \
    yt="youtube-dl --add-metadata -i" \
    yta="yt -x -f bestaudio/best" \
    ffmpeg="ffmpeg -hide_banner" \
    ka="killall" \
    g="git" \
    conf="g --git-dir=$HOME/.dotfiles --work-tree=$HOME" \
    p="pacman" \
    f="$FILE" \
    e="$EDITOR" \
    vmu="sv up libvirtd virtlogd virtlockd" \
    vmd="sv down libvirtd virtlogd virtlockd"

# Runs zathura independently.
z () {
        zathura $* & disown
}

# sv, but for user services
usv () {
        env SVDIR=$HOME/.local/runit/sv sv "$@"
}

# Useful sv shortcuts
alias \
    svs="sv s /run/runit/service/*" \
    usvs="sv s $HOME/.local/runit/sv/*"

# Add color to commands
alias \
    ls="ls -hN --color=auto --group-directories-first" \
    grep="grep --color=auto" \
    diff="diff --color=auto" \
    ccat="highlight --out-format=ansi"
