#!/bin/bash

# Use neovim for vim when possible.
command -v nvim >/dev/null && alias vim="nvim" vimdiff="nvim -d"

# Stop making me type sudo >:|
for x in timeshift mount umount sv pacman updatedb poweroff reboot ; do
        alias $x="sudo $x"
done

# Adds verbosity where we like it and shortens common commands.
alias \
	bup="sudo timeshift --create" \
        res="sudo timeshift --restore" \
	upg="yay -Syu || sudo pacman -Syu" \
	clr="clear" \
	bat="cat /sys/class/power_supply/BAT?/capacity" \
	cp="cp -iv" \
	mv="mv -iv" \
	rm="rm -v" \
	mkd="mkdir -pv" \
        rmd="rmdir -pv" \
	yt="youtube-dl --add-metadata -i" \
	yta="yt -x -f bestaudio/best" \
	ffmpeg="ffmpeg -hide_banner" \
  	ka="killall" \
	g="git" \
        ga="g add" \
        gf="g fetch" \
        gs="g status" \
        gc="g commit" \
        gpl="g pull" \
        gps="g push" \
        gud="gf; gs" \
	conf="g --git-dir=$HOME/.dotfiles --work-tree=$HOME" \
	confa="conf add" \
	conff="conf fetch" \
	confs="conf status" \
	confc="conf commit -a" \
	confpl="conf pull" \
	confps="conf push" \
	confud="conff; confs" \
        p="pacman" \
	trem="transmission-remote" \
	YT="youtube-viewer" \
	f="$FILE" \
	e="$EDITOR"

# Runs zathura independently.
z () {
	zathura $* & disown
}

# Adds color to commands.
alias \
	ls="ls -hN --color=auto --group-directories-first" \
	grep="grep --color=auto" \
	diff="diff --color=auto" \
	ccat="highlight --out-format=ansi"

# Enables the `pauseallmpv` command.
alias mpv="mpv --input-ipc-server=/tmp/mpvsoc$(date +%s)"

# Some other stuff
alias \
	magit="nvim -c MagitOnly" \
	ref="shortcuts >/dev/null; source ~/.config/shortcutrc"
