#!/bin/bash

# Use neovim when possible
command -v nvim >/dev/null && alias vim="nvim" vimdiff="nvim -d"

# Stop making me type sudo >:|
for x in docker timeshift mount umount pacman updatedb poweroff shutdown reboot ; do
        alias $x="sudo $x"
done

# Adds verbosity and shorten common commands
alias \
    bup="sudo timeshift --create" \
    res="sudo timeshift --restore" \
    upg="paru -Syu --noconfirm && doom -y upgrade && doom doctor" \
    upgp="docker stop portainer && docker rm portainer && docker pull portainer/portaine-ce:latest && docker run -d -p 9000:9000 --name=portainer --restart=always -v /var/run/docker.sock:/var/run/docker.sock -v /docker/appdata/portainer:/data portainer/portainer-ce:latest" \
    upgd="doom upgrade && doom doctor" \
    bat="cat /sys/class/power_supply/BAT?/capacity" \
    cp="cp -iv" \
    mv="mv -iv" \
    rm="rm -v" \
    mkd="mkdir -pv" \
    rmd="rmdir -v" \
    ka="killall" \
    g="git" \
    conf="g --git-dir=$HOME/.dotfiles --work-tree=$HOME" \
    p="paru" \
    f="$FILE" \
    e="$EDITOR" \
    sv="sudo dinitctl" \
    svs="sudo dinitctl list" \
    usv="dinitctl" \
    usvs="sudo dinitctl list"

# Runs zathura independently.
z () {
        zathura $* & disown
}

# Add color to commands
alias \
    ls="ls -hN --color=auto --group-directories-first" \
    grep="grep --color=auto" \
    diff="diff --color=auto" \
    ccat="highlight --out-format=ansi"
