assume_yes = true
cleanup = true

disable = ["nix"]
ignore_failures = ["vim"]
#only = ["system", "emacs"]

[git]
max_concurrency = 5
repos = [
      "~/.dotfiles",
      "~",
      "~/episteme",
      "~/org-roam/*",
      "~/dev/*"
]
arguments = "--rebase --autostash"

[pre_commands]

[commands]
"Doom Sync" = "$XDG_CONFIG_HOME/emacs/bin/doom sync -p && $XDG_CONFIG_HOME/emacs/bin/doom doctor"
"Xmonad Recompile" = "/usr/bin/xmonad --recompile"
"Docker" = "$HOME/.local/bin/dockerup"
"Nix" = "/usr/bin/nix-channel --update && /usr/bin/nix-env --upgrade"

[linux]
arch_package_manager = "paru"
show_arch_news = true
