assume_yes = true
cleanup = true

#disable = ["nix"]
ignore_failures = ["vim"]
#only = ["system", "emacs"]

[git]
max_concurrency = 5
repos = [
      "~/.dotfiles",
      "~",
      "~/episteme",
      "~/org-roam/*",
      "~/dev/*"
]
arguments = "--rebase --autostash"

[pre_commands]

[commands]
"Doom Sync" = "$XDG_CONFIG_HOME/emacs/bin/doom sync -p && $XDG_CONFIG_HOME/emacs/bin/doom doctor"
"Xmonad Recompile" = "xmonad --recompile"
"Docker" = "$HOME/.local/bin/dockerup"
"Nix GC" = "nix-env --delete-generations 14d && nix-store --gc"

[linux]
arch_package_manager = "paru"
show_arch_news = true
