# Don't ask for confirmations
assume_yes = true

# Disable specific steps - same options as the command line flag
#disable = ["system", "emacs"]

# Ignore failures for these steps
#ignore_failures = ["powershell"]

# Run specific steps - same options as the command line flag
#only = ["system", "emacs"]

# Cleanup temporary or old files
cleanup = true

[git]
max_concurrency = 5
repos = [
      "~/episteme",
      "~/dotfiles",
      "~/dev/*"
]
arguments = "--rebase --autostash"

# Commands to run before anything
[pre_commands]
#"Emacs Snapshot" = "rm -rf ~/.emacs.d/elpa.bak && cp -rl ~/.emacs.d/elpa ~/.emacs.d/elpa.bak"

[commands]
"Xmonad Recompile" = "/usr/bin/xmonad --recompile"

[linux]
arch_package_manager = "paru"
#yay_arguments = "--nodevel"
show_arch_news = true
