assume_yes = true
cleanup = true

#disable = ["system", "emacs"]
ignore_failures = ["vim"]
#only = ["system", "emacs"]

[git]
max_concurrency = 5
repos = [
      "~/.dotfiles",
      "~",
      "~/episteme",
      "~/org-roam/*",
      "~/dev/*"
]
arguments = "--rebase --autostash"

[pre_commands]

[commands]
"Doom Sync" = "$XDG_CONFIG_HOME/emacs/bin/doom sync -p && $XDG_CONFIG_HOME/emacs/bin/doom doctor"
"Xmonad Recompile" = "/usr/bin/xmonad --recompile"
"Reflector" = "$HOME/.local/bin/mirrorlist --sort rate --save /etc/pacman.d/mirrorlist --threads 5"
"Docker" = "$HOME/.local/bin/dockerup"

[linux]
arch_package_manager = "paru"
show_arch_news = true
